//! Base type for all journal items (transactions and postings).
//!
//! This module provides the `Item` struct, a Rust port of Ledger's `item_t`.
//! Every entry in a journal -- whether a full transaction or an individual
//! posting -- contains an `Item` as its base fields. This provides:
//!
//!   - **Clearing state**: Uncleared, Cleared, Pending
//!   - **Dates**: a primary date and an optional auxiliary/effective date
//!   - **Notes and metadata**: free-form comments plus structured key/value tags
//!   - **Source position**: file path and line range for error reporting
//!   - **Flags**: bit flags for generated, temporary, inferred items

use std::collections::HashMap;
use std::fmt;

use chrono::NaiveDate;

// ---------------------------------------------------------------------------
// Item flags (matching C++ #defines)
// ---------------------------------------------------------------------------

/// Normal (no flags set).
pub const ITEM_NORMAL: u32 = 0x00;
/// Generated by an automated transaction or other rule.
pub const ITEM_GENERATED: u32 = 0x01;
/// Temporary item, not persisted.
pub const ITEM_TEMP: u32 = 0x02;
/// Note is on the next line rather than inline.
pub const ITEM_NOTE_ON_NEXT_LINE: u32 = 0x04;
/// Amount was inferred (auto-balanced).
pub const ITEM_INFERRED: u32 = 0x08;

// ---------------------------------------------------------------------------
// ItemState enum
// ---------------------------------------------------------------------------

/// Clearing state for a journal item.
///
/// In Ledger's journal syntax, a transaction or posting may carry a clearing
/// mark: `*` for Cleared, `!` for Pending, or no mark for Uncleared.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ItemState {
    Uncleared = 0,
    Cleared = 1,
    Pending = 2,
}

impl Default for ItemState {
    fn default() -> Self {
        ItemState::Uncleared
    }
}

impl fmt::Display for ItemState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ItemState::Uncleared => write!(f, ""),
            ItemState::Cleared => write!(f, "*"),
            ItemState::Pending => write!(f, "!"),
        }
    }
}

// ---------------------------------------------------------------------------
// Position
// ---------------------------------------------------------------------------

/// Records the source file location of a parsed journal item.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Position {
    /// Filesystem path of the journal file.
    pub pathname: String,
    /// Line number where the item begins (1-based).
    pub beg_line: usize,
    /// Line number where the item ends (inclusive).
    pub end_line: usize,
    /// Stream offset where the item begins.
    pub beg_pos: usize,
    /// Stream offset just past the item's last byte.
    pub end_pos: usize,
    /// Global parse-order sequence number.
    pub sequence: usize,
}

impl Position {
    pub fn new() -> Self {
        Self {
            pathname: String::new(),
            beg_line: 0,
            end_line: 0,
            beg_pos: 0,
            end_pos: 0,
            sequence: 0,
        }
    }
}

impl Default for Position {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

/// Base fields for all journal items: transactions and postings.
///
/// Both `Transaction` and `Post` embed an `Item` to share these fields:
/// flags, clearing state, dates, notes, metadata tags, and source position.
#[derive(Debug, Clone)]
pub struct Item {
    /// Bit flags (ITEM_NORMAL, ITEM_GENERATED, etc.).
    pub flags: u32,
    /// Clearing state.
    pub state: ItemState,
    /// Primary date.
    pub date: Option<NaiveDate>,
    /// Auxiliary (effective) date.
    pub date_aux: Option<NaiveDate>,
    /// Free-form note text from `;` comment lines.
    pub note: Option<String>,
    /// Source file position for error reporting.
    pub position: Option<Position>,
    /// Structured metadata tags (key -> value).
    metadata: Option<HashMap<String, String>>,
}

impl Item {
    /// Create a new Item with default values.
    pub fn new() -> Self {
        Self {
            flags: ITEM_NORMAL,
            state: ItemState::Uncleared,
            date: None,
            date_aux: None,
            note: None,
            position: None,
            metadata: None,
        }
    }

    /// Create a new Item with the given flags.
    pub fn with_flags(flags: u32) -> Self {
        let mut item = Self::new();
        item.flags = flags;
        item
    }

    // ---- date helpers -------------------------------------------------------

    /// Return true if a primary date is set.
    pub fn has_date(&self) -> bool {
        self.date.is_some()
    }

    // ---- flag helpers -------------------------------------------------------

    /// Return true if all bits in `flag` are set.
    pub fn has_flags(&self, flag: u32) -> bool {
        (self.flags & flag) == flag
    }

    /// Set the given flag bits.
    pub fn add_flags(&mut self, flag: u32) {
        self.flags |= flag;
    }

    /// Clear the given flag bits.
    pub fn drop_flags(&mut self, flag: u32) {
        self.flags &= !flag;
    }

    // ---- metadata / tag system ----------------------------------------------

    /// Return true if the metadata contains `tag` (case-sensitive).
    pub fn has_tag(&self, tag: &str) -> bool {
        match &self.metadata {
            Some(m) => m.contains_key(tag),
            None => false,
        }
    }

    /// Return the value associated with `tag`, or None.
    pub fn get_tag(&self, tag: &str) -> Option<&str> {
        match &self.metadata {
            Some(m) => m.get(tag).map(|s| s.as_str()),
            None => None,
        }
    }

    /// Set a metadata tag. If `value` is not provided it defaults to empty string.
    pub fn set_tag(&mut self, tag: &str, value: &str) {
        if self.metadata.is_none() {
            self.metadata = Some(HashMap::new());
        }
        self.metadata
            .as_mut()
            .unwrap()
            .insert(tag.to_string(), value.to_string());
    }

    // ---- copy details -------------------------------------------------------

    /// Copy all mutable fields from `other`.
    pub fn copy_details(&mut self, other: &Item) {
        self.flags = other.flags;
        self.state = other.state;
        self.date = other.date;
        self.date_aux = other.date_aux;
        self.note = other.note.clone();
        self.position = other.position.clone();
        self.metadata = other.metadata.clone();
    }

    // ---- description --------------------------------------------------------

    /// Return a human-readable description for error messages.
    pub fn description(&self) -> String {
        if let Some(pos) = &self.position {
            format!("item at line {}", pos.beg_line)
        } else {
            "generated item".to_string()
        }
    }
}

impl Default for Item {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::NaiveDate;

    #[test]
    fn item_state_default() {
        assert_eq!(ItemState::default(), ItemState::Uncleared);
    }

    #[test]
    fn item_state_display() {
        assert_eq!(ItemState::Cleared.to_string(), "*");
        assert_eq!(ItemState::Pending.to_string(), "!");
        assert_eq!(ItemState::Uncleared.to_string(), "");
    }

    #[test]
    fn position_default() {
        let pos = Position::new();
        assert_eq!(pos.beg_line, 0);
        assert_eq!(pos.pathname, "");
    }

    #[test]
    fn item_new_defaults() {
        let item = Item::new();
        assert_eq!(item.flags, ITEM_NORMAL);
        assert_eq!(item.state, ItemState::Uncleared);
        assert!(item.date.is_none());
        assert!(item.date_aux.is_none());
        assert!(item.note.is_none());
        assert!(item.position.is_none());
        assert!(!item.has_date());
    }

    #[test]
    fn item_with_flags() {
        let item = Item::with_flags(ITEM_GENERATED | ITEM_TEMP);
        assert!(item.has_flags(ITEM_GENERATED));
        assert!(item.has_flags(ITEM_TEMP));
        assert!(!item.has_flags(ITEM_INFERRED));
    }

    #[test]
    fn item_flag_manipulation() {
        let mut item = Item::new();
        item.add_flags(ITEM_GENERATED);
        assert!(item.has_flags(ITEM_GENERATED));
        item.drop_flags(ITEM_GENERATED);
        assert!(!item.has_flags(ITEM_GENERATED));
    }

    #[test]
    fn item_metadata_tags() {
        let mut item = Item::new();
        assert!(!item.has_tag("Payee"));
        assert!(item.get_tag("Payee").is_none());

        item.set_tag("Payee", "Store");
        assert!(item.has_tag("Payee"));
        assert_eq!(item.get_tag("Payee"), Some("Store"));

        item.set_tag("bare_tag", "");
        assert!(item.has_tag("bare_tag"));
    }

    #[test]
    fn item_dates() {
        let mut item = Item::new();
        assert!(!item.has_date());

        let d = NaiveDate::from_ymd_opt(2024, 1, 15).unwrap();
        item.date = Some(d);
        assert!(item.has_date());
        assert_eq!(item.date, Some(d));
    }

    #[test]
    fn item_copy_details() {
        let mut src = Item::new();
        src.flags = ITEM_GENERATED;
        src.state = ItemState::Cleared;
        src.date = NaiveDate::from_ymd_opt(2024, 3, 1);
        src.note = Some("test note".to_string());
        src.set_tag("key", "val");

        let mut dst = Item::new();
        dst.copy_details(&src);
        assert_eq!(dst.flags, ITEM_GENERATED);
        assert_eq!(dst.state, ItemState::Cleared);
        assert_eq!(dst.date, src.date);
        assert_eq!(dst.note, Some("test note".to_string()));
        assert_eq!(dst.get_tag("key"), Some("val"));
    }

    #[test]
    fn item_description_with_position() {
        let mut item = Item::new();
        item.position = Some(Position {
            pathname: "test.dat".to_string(),
            beg_line: 42,
            ..Position::default()
        });
        assert_eq!(item.description(), "item at line 42");
    }

    #[test]
    fn item_description_generated() {
        let item = Item::new();
        assert_eq!(item.description(), "generated item");
    }
}
